.suggestions
{
	position:relative;
	top: 1px;
	_top: 0px;
	z-index:2800 !important;
}


.autocomplete
{
	
	background: #FFFFFF !important;
	border: solid 2px #8B9CD3 !important;
	width: 300px !important;
	font-family: 'Arial','Helvetica',sans-serif !important;
	font-size: 91% !important;
	z-index:2900 !important;
	display:block;
}

.autocomplete DIV
{
	padding: 2px 4px 2px 10px !important;
	z-index:3000 !important;
	display:block;
	cursor:default;	
}
