@isTest
public class CP_Flow_Query_Groups_Test {
    
  //  @testSetup static void testSetup(){
       // Group g = new Group(Type='Queue', Name='MyTestQueue');
       // insert g;
        
        //QueueSObject q = new QueueSObject(SobjectType='contact', QueueId=g.Id);
       // insert q;        
   // }
    
  @IsTest
    static void testgetQueueId(){
       // List<Group> baseQueueId = new List<Group>();
        String result;
       // CP_Flow_Query_Groups.RequestVariables target;
       // list<CP_Flow_Query_Groups.RequestVariables> findList = new list<CP_Flow_Query_Groups.RequestVariables>();
       // target.groupName='CP_Contact_US_1';
       // findList.add(target);
       // baseQueueId = [Select Id from group WHERE DeveloperName =: 'MyTestQueue'];
       // result = CP_Flow_Query_Groups.getId(findList)[0];
       // system.assertEquals((String)baseQueueId[0].id, result);
    }
}