@isTest private without sharing class DB_Custom_WIN_Contributor_c
{
    @isTest (SeeAllData=true)
    private static void testTrigger()
    {
    //@@TODO:  rewrite this test
        /*CRMfusionDBR101.DB_Globals.triggersDisabled = true;
        sObject testData = CRMfusionDBR101.DB_TriggerHandler.createTestData( WIN_Contributor__c.getSObjectType() );
        Test.startTest();
        insert testData;
        update testData;
        CRMfusionDBR101.DB_Globals.generateCustomTriggerException = true;
        update testData;
        delete testData;
        Test.stopTest();*/
    }
}