/**
 * Auto Generated and Deployed by the Declarative Lookup Rollup Summaries Tool package (dlrs)
 **/
@IsTest
private class dlrs_Related_Cases_and_OrgsTest
{
    private static testmethod void testTrigger()
    {
        // Force the dlrs_Related_Cases_and_OrgsTrigger to be invoked, fails the test if org config or other Apex code prevents this.
        dlrs.RollupService.testHandler(new Related_Cases_and_Orgs__c());
    }
}