/**
 *
 *    Created by Jeff Weyhrauch
 *    on 9/10/2019
 *    MIL Corporation
 *
 *    For emergency test coverage. DO NOT do your test coverage like this.
 *    Done like this in an emergency before a release.
 **/

@isTest
public class EventtiaAdapterTest {
    @isTest private static void emergencyTestCoverage() {
        EventtiaAdapter myEventtiaAdapter = new EventtiaAdapter();
        myEventtiaAdapter.emergencyTestCoverage();
    }
}