public class PaymentAuthenticationDetails {
	public Id paymentId;
	public String paymentIdentifier;
	public String remoteAccountName;
	public String transactionType;
	public String transactionAmount;
	public String successUrl;
	public String cancelUrl;
	public String accountHolderName;
	public String billingAddress;
	public String billingAddress2;
	public String billingCity;
	public String billingStateCode;
	public String billingZip;
	public String billingCountryCode;
	public String email;
	public String accountType;
	public String error;
}